name = 'favorites'
position = 0

[[sound]]
name = 'Krasser Kai Uwe'
path = 'krasserKaiUwe.mp3'

[[sound]]
name = 'Ich rascht aus'
path = 'ich-rascht-aus.flac'

[[sound]]
name = 'Warteee EEEY'
path = 'warteEYY.mp3'

[[sound]]
name = 'Woran hats gelegen'
path = 'Worahnhatsgelegen.mp3'

[[sound]]
name = 'Kranplätze'
path = 'https://alleswirdaushackgemacht.de/audio/ronny/kranplaetze.mp3'

[[sound]]
name = 'Vollidioten'
path = 'https://alleswirdaushackgemacht.de/audio/ronny/vollidioten.mp3'

[[sound]]
name = 'Hierhoch'
path = 'https://alleswirdaushackgemacht.de/audio/ronny/hierhoch.mp3'

[[sound]]
name = 'wo sind die brillen'
path = 'wo ist der latest shit.mp3'
start = 18

[[sound]]
end = 6.7
name = 'wo ist der latest shit'
path = 'wo ist der latest shit.mp3'

[[sound]]
name = 'Wer wird Millionär - Showstart'
path = 'https://www.myinstants.com//media/sounds/wer-wird-millionar-soundtracks-soundstart.mp3'

[[sound]]
name = 'Summasummarum'
path = 'Summasummarum.mp3'

[[sound]]
hotkey = 'CTRL-SHIFT-BACKSPACE'
name = 'Soldier of Fortune'
path = 'vodka/Razor1911 - Soldier Of Fortune intro.xm'

[[sound]]
name = '''It's time to duel'''
path = 'its-time-to-duel.ogg'

[[sound]]
name = 'the one and only'
path = 'oneandonly.wav'

[[sound]]
name = 'steam incoming'
path = 'https://www.myinstants.com/media/sounds/message_2.mp3'

[[sound]]
name = 'crab rave'
path = 'https://www.myinstants.com/media/sounds/original_zeowGW1.mp3'

[[sound]]
hotkey = 'CTRL-P'
name = 'Nicht so tief, Rüdiger!'
path = 'nicht-so-tief-rudiger.mp3'
