[package]
name = "soundboard"
version = "0.1.0"
description = "cross-plattform soundboard: play sounds over your microphone"
authors = ["Karl Skomski <karl@skomski.com>", "Corin Baurmann <corin.baurmann@fu-berlin.de>", "Elena Frank <elena.frank@protonmail.com>"]
categories = ["multimedia::audio"]
edition = "2018"

[dependencies]

cpal = "0.11"
rodio = "0.11"
hotkey = { path = "extern/hotkey-rs", version = "0.3" }
iced = { version = "0.1", features = ["tokio"] }
iced_native = "0.2"
clap = "3.0.0-beta.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.7.1"
random_color = "0.4"
ringbuf = "0.2.1"
reqwest = { version = "0.10", features = ["blocking"] }
regex = "1"
strum = "0.18"
strum_macros = "0.18"
crossbeam-channel = "0.4"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
mp3-duration = "0.1.9"
ogg_metadata = "0.4"

[build-dependencies]
fs_extra = "1.1.0"
