[package]
name = "soundboard"
version = "0.1.0"
description = "cross-plattform soundboard: play sounds over your microphone"
authors = ["Karl Skomski <karl@skomski.com>", "Corin Baurmann <corin.baurmann@fu-berlin.de>", "Elena Frank <elena.frank@protonmail.com>"]
categories = ["multimedia::audio"]
license = "Unlicense"
repository = "https://github.com/gamebooster/soundboard"
edition = "2018"
exclude = [
    "/soundboards",
    "/extern"
]

[profile.release]
lto = true

[features]
default = ["mp3", "flac", "vorbis", "wav", "http", "gui"]
mp3 = ["minimp3", "mp3-duration"]
flac = ["claxon"]
vorbis = ["lewton", "ogg_metadata"]
wav = ["hound"]
xm = ["libxm-soundboard"]
http = ["warp", "futures"]
gui = ["iced", "iced_native"]
autoloop = ["libpulse-binding", "ctrlc"]
telegram = ["tgbot", "fuzzy-matcher"]

[dependencies]
miniaudio = "0.6"
hotkey-soundboard = { path = "extern/hotkey-rs", version = "0.0.1" }
clap = "3.0.0-beta.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.7"
reqwest = { version = "0.10", features = ["blocking"] }
regex = "1"
strum = "0.18"
strum_macros = "0.18"
crossbeam-channel = "0.4"
tokio = { version = "0.2", features = ["macros", "full"] }
once_cell = "1.4"
winit = "0.22"
dirs = "3"

tgbot = { version = "0.10", optional = true }
fuzzy-matcher = {version = "0.3", optional = true}

ctrlc = { version = "3.1.4", features = ["termination"], optional = true}
libpulse-binding = { version = "2.0", features = ["pa_latest_common"], optional = true }

iced = { version = "0.1", optional = true, features = ["tokio"] }
iced_native = {version = "0.2", optional = true }

warp = {version = "0.2", optional = true }
futures = {version = "0.3", optional = true }

mp3-duration = {version = "0.1.10", optional = true }
ogg_metadata = {version = "0.4", optional = true }
minimp3 = {version = "0.3", optional = true }
hound = {version = "3", optional = true }
lewton = {version = "0.10", optional = true }
claxon = {version = "0.4", optional = true }
libxm-soundboard = {version = "0.0.1", path = "extern/libxm-rs", optional = true }

[build-dependencies]
fs_extra = "1"