# input_device = 0
# output_device = 1
# loopback_device = 2

[[sounds]]
name = "Nicht so tief Rüdiger!"
path = "nicht-so-tief-rudiger.mp3"
hotkey_modifier = ["CTRL"]
hotkey_key = "P"

[[sounds]]
name = "vodka_dance"
path = "vodka_dance.mp3"
hotkey_modifier = ["CTRL", "SHIFT"]
hotkey_key = "P"