# input_device = 0
# output_device = 1
loopback_device = 0

stop_hotkey = "ALT-S"

[[soundboard]]
name = "default"

    [[soundboard.sound]]
    name = "Nicht so tief, Rüdiger!"
    path = "sounds/nicht-so-tief-rudiger.mp3"
    hotkey = "CTRL-P"

    [[soundboard.sound]]
    name = "Razor1911 Vodka Dance"
    path = "sounds/vodka/vodka_dance.mp3" # later xm
    hotkey = "CTRL-SHIFT-BACKSPACE"

    [[soundboard.sound]]
    name = "It's time to duel"
    path = "sounds/its-time-to-duel.ogg"
    hotkey = "ALT-9"

    [[soundboard.sound]]
    name = "Ich rascht aus"
    path = "sounds/ich-rascht-aus.flac"
    hotkey = "ALT-8"

    [[soundboard.sound]]
    name = "steam incoming"
    path = "https://www.myinstants.com/media/sounds/message_2.mp3"
    hotkey = "ALT-7"

    [[soundboard.sound]]
    name = "crab rave"
    path = "https://www.myinstants.com/media/sounds/original_zeowGW1.mp3"

    [[soundboard.sound]]
    name="BRUH"
    path="https://www.myinstants.com//media/sounds/movie_1.mp3"

    [[soundboard.sound]]
    name="Female Orgasm"
    path="https://www.myinstants.com//media/sounds/epic.swf_1.mp3"

    [[soundboard.sound]]
    name="TeamSpeak 3"
    path="https://www.myinstants.com//media/sounds/untitled_291.mp3"

    [[soundboard.sound]]
    name="Kann es sein das du Dumm bist"
    path="https://www.myinstants.com//media/sounds/kann-es-sein-das-du-dumm-bist-oder-so-was.mp3"

[[soundboard]]
name = "Myinstants.com"
path = "myinstants_soundboard.toml"

# [[soundboard]]
# name = "Deutsche Memez"
# path = "deutsche_memes.toml"