[package]
name = "libxm-soundboard"
version = "0.0.1"
authors = ["Dan Spencer <dan@atomicpotato.net>", "Karl Skomski <karl@skomski.com>"]
description = "An modified fork of libxm-rs https://github.com/nukep/libxm-rs for internal usage with the project soundboard"
readme = "README.md"
license = "Unlicense"
build = "build.rs"
repository = "https://github.com/gamebooster/soundboard/tree/master/extern/libxm-rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
