name: BuildRelease
on:
  push:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install autoconf
        run: sudo apt-get install autoconf libtool automake
      - name: Build soundboard binary
        run: cargo build --verbose --release
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-debian-linux-gnu
          path: target/release/soundboard

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install llvm
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install llvm --global
          echo "::set-env name=PATH::$env:PATH"
      - name: Build soundboard binary
        env:
          LIBCLANG_PATH: "C:\\ProgramData\\scoop\\apps\\llvm\\current\\bin"
        run: cargo build --verbose --release
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-pc-windows-msvc
          path: target/release/soundboard.exe

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install opus
        run: |
          wget https://homebrew.bintray.com/bottles/pkg-config-0.29.2_3.catalina.bottle.tar.gz
          tar xvf pkg-config-0.29.2_3.catalina.bottle.tar.gz pkg-config/0.29.2_3/bin/
          cp -a pkg-config/0.29.2_3/bin /usr/local
          wget https://homebrew.bintray.com/bottles/opus-1.3.1.catalina.bottle.1.tar.gz
          tar -xvf opus-1.3.1.catalina.bottle.1.tar.gz opus/1.3.1/lib opus/1.3.1/include
          cp -a opus/1.3.1/lib /usr/local
          cp -a opus/1.3.1/include /usr/local
      - name: Build soundboard binary
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.14
        run: cargo build --verbose --release
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-apple-darwin
          path: target/release/soundboard
