name: BuildRelease
on:
  push:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install autoconf and pulseaudio
        run: sudo apt-get install autoconf libtool automake libpulse0 libgtk-3-dev
      - name: Build soundboard binary
        run: cargo build --verbose --release --features full,autoloop
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-debian-linux-gnu
          path: target/release/soundboard

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install llvm
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install llvm --global
          echo $env:Path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Build soundboard binary
        env:
          LIBCLANG_PATH: "C:\\ProgramData\\scoop\\apps\\llvm\\current\\bin"
        run: cargo build --verbose --release --features full
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-pc-windows-msvc
          path: target/release/soundboard.exe

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install opus
        run: |
          brew install opus
      - name: Build soundboard binary
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.14
          OPUS_STATIC: 1
          OPUS_NO_PKG: 1
          OPUS_LIB_DIR: "/usr/local/lib"
        run: cargo build --verbose --release --features full
      - name: Archive soundboard binary
        uses: actions/upload-artifact@v2
        with:
          name: soundboard-x86_64-apple-darwin
          path: target/release/soundboard
