name: FormatAndClippy
on: [push, pull_request]
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt
    - uses: actions/checkout@master
    - name: Check format
      run: cargo fmt --all -- --check

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: Install alsa
        run: sudo apt-get install alsa alsa-tools libasound2-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features